//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.18 at 11:30:59 AM CEST 
//


package pl.soapservice.wstest;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.soapservice.wstest package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.soapservice.wstest
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetPhoneResponse }
     * 
     */
    public GetPhoneResponse createGetPhoneResponse() {
        return new GetPhoneResponse();
    }

    /**
     * Create an instance of {@link InsertPhoneRequest }
     * 
     */
    public InsertPhoneRequest createInsertPhoneRequest() {
        return new InsertPhoneRequest();
    }

    /**
     * Create an instance of {@link GetPhoneRequest }
     * 
     */
    public GetPhoneRequest createGetPhoneRequest() {
        return new GetPhoneRequest();
    }

    /**
     * Create an instance of {@link GetPhoneByModelResponse }
     * 
     */
    public GetPhoneByModelResponse createGetPhoneByModelResponse() {
        return new GetPhoneByModelResponse();
    }

    /**
     * Create an instance of {@link SoapComponent }
     * 
     */
    public SoapComponent createSoapComponent() {
        return new SoapComponent();
    }

    /**
     * Create an instance of {@link GetAllPhonesRequest }
     * 
     */
    public GetAllPhonesRequest createGetAllPhonesRequest() {
        return new GetAllPhonesRequest();
    }

    /**
     * Create an instance of {@link InsertPhoneResponse }
     * 
     */
    public InsertPhoneResponse createInsertPhoneResponse() {
        return new InsertPhoneResponse();
    }

    /**
     * Create an instance of {@link DeletePhoneResponse }
     * 
     */
    public DeletePhoneResponse createDeletePhoneResponse() {
        return new DeletePhoneResponse();
    }

    /**
     * Create an instance of {@link UpdatePhoneResponse }
     * 
     */
    public UpdatePhoneResponse createUpdatePhoneResponse() {
        return new UpdatePhoneResponse();
    }

    /**
     * Create an instance of {@link DeletePhoneRequest }
     * 
     */
    public DeletePhoneRequest createDeletePhoneRequest() {
        return new DeletePhoneRequest();
    }

    /**
     * Create an instance of {@link UpdatePhoneRequest }
     * 
     */
    public UpdatePhoneRequest createUpdatePhoneRequest() {
        return new UpdatePhoneRequest();
    }

    /**
     * Create an instance of {@link GetAllPhonesResponse }
     * 
     */
    public GetAllPhonesResponse createGetAllPhonesResponse() {
        return new GetAllPhonesResponse();
    }

    /**
     * Create an instance of {@link GetPhoneByModelRequest }
     * 
     */
    public GetPhoneByModelRequest createGetPhoneByModelRequest() {
        return new GetPhoneByModelRequest();
    }

    /**
     * Create an instance of {@link SoapPhone }
     * 
     */
    public SoapPhone createSoapPhone() {
        return new SoapPhone();
    }

}
