
package restClient.soapclasses;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PhonesPort", targetNamespace = "/SoapService/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PhonesPort {


    /**
     * 
     * @param deletePhoneRequest
     * @return
     *     returns restClient.wsclient.DeletePhoneResponse
     */
    @WebMethod
    @WebResult(name = "deletePhoneResponse", targetNamespace = "http://soapservice.pl/wstest", partName = "deletePhoneResponse")
    public DeletePhoneResponse deletePhone(
        @WebParam(name = "deletePhoneRequest", targetNamespace = "http://soapservice.pl/wstest", partName = "deletePhoneRequest")
        DeletePhoneRequest deletePhoneRequest);

    /**
     * 
     * @param insertPhoneRequest
     * @return
     *     returns restClient.wsclient.InsertPhoneResponse
     */
    @WebMethod
    @WebResult(name = "insertPhoneResponse", targetNamespace = "http://soapservice.pl/wstest", partName = "insertPhoneResponse")
    public InsertPhoneResponse insertPhone(
        @WebParam(name = "insertPhoneRequest", targetNamespace = "http://soapservice.pl/wstest", partName = "insertPhoneRequest")
        InsertPhoneRequest insertPhoneRequest);

    /**
     * 
     * @param updatePhoneRequest
     * @return
     *     returns restClient.wsclient.UpdatePhoneResponse
     */
    @WebMethod
    @WebResult(name = "updatePhoneResponse", targetNamespace = "http://soapservice.pl/wstest", partName = "updatePhoneResponse")
    public UpdatePhoneResponse updatePhone(
        @WebParam(name = "updatePhoneRequest", targetNamespace = "http://soapservice.pl/wstest", partName = "updatePhoneRequest")
        UpdatePhoneRequest updatePhoneRequest);

    /**
     * 
     * @param getPhoneRequest
     * @return
     *     returns restClient.wsclient.GetPhoneResponse
     */
    @WebMethod
    @WebResult(name = "getPhoneResponse", targetNamespace = "http://soapservice.pl/wstest", partName = "getPhoneResponse")
    public GetPhoneResponse getPhone(
        @WebParam(name = "getPhoneRequest", targetNamespace = "http://soapservice.pl/wstest", partName = "getPhoneRequest")
        GetPhoneRequest getPhoneRequest);

    /**
     * 
     * @param getPhoneByModelRequest
     * @return
     *     returns restClient.wsclient.GetPhoneByModelResponse
     */
    @WebMethod
    @WebResult(name = "getPhoneByModelResponse", targetNamespace = "http://soapservice.pl/wstest", partName = "getPhoneByModelResponse")
    public GetPhoneByModelResponse getPhoneByModel(
        @WebParam(name = "getPhoneByModelRequest", targetNamespace = "http://soapservice.pl/wstest", partName = "getPhoneByModelRequest")
        GetPhoneByModelRequest getPhoneByModelRequest);

    /**
     * 
     * @param getAllPhonesRequest
     * @return
     *     returns restClient.wsclient.GetAllPhonesResponse
     */
    @WebMethod
    @WebResult(name = "getAllPhonesResponse", targetNamespace = "http://soapservice.pl/wstest", partName = "getAllPhonesResponse")
    public GetAllPhonesResponse getAllPhones(
        @WebParam(name = "getAllPhonesRequest", targetNamespace = "http://soapservice.pl/wstest", partName = "getAllPhonesRequest")
        GetAllPhonesRequest getAllPhonesRequest);

}
